# Generated by Django 5.0.1 on 2024-02-03 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_profile_password_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
